/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;
import java.util.ArrayList;

import neuralNetwork.NeuralNetwork;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        double [][] x={
            {0,0},
            {0,1},
            {0,1},
            {1,1}
        };
        double [][] y={
            {0},{1},{1},{0}
        };
        int []nodesInLayers={2,10,1};
        NeuralNetwork neuralNetwork=new NeuralNetwork(nodesInLayers);
        for (double d[]:x){
            ArrayList<Double> output = neuralNetwork.predict(d);
            System.out.println(output.toString());
        }
    }
}
